import type { FantasySpot } from "./types";

function nowMinus(minutes: number): string {
  return new Date(Date.now() - minutes * 60_000).toISOString();
}

const base = {
  legend_title: null,
  legend_story: null,
  legend_tagline: null,
  location_name: null,
  image_url: null,
  user_id: null,
  is_public: true,
  believe_count: 0,
  visited_count: 0,
  want_to_go_count: 0,
};

export const SEED_SPOTS: FantasySpot[] = [
  {
    ...base,
    id: "seed-sky-station",
    title: "雲上行き0番ホーム",
    catch_copy: "終電後、空へ向かう列車が来る。",
    story:
      "駅の端には、案内板に載っていない0番ホームがある。そこに停まる列車は、地上ではなく雲の上へ向かうらしい。",
    latitude: 35.6585,
    longitude: 139.7016,
    seed_text: "ここに空へ行くホームがあったら",
    genre: "fantasy",
    place_type: "station",
    mood: "emotional",
    quest: "この場所で空を見上げ、雲の形をコメントしてみよう。",
    tags: ["駅", "空", "ファンタジー"],
    image_theme: "sky_station",
    generation_type: "template",
    level: 2,
    comment_count: 3,
    believe_count: 5,
    visited_count: 12,
    want_to_go_count: 128,
    author_name: "ゲスト旅人",
    created_at: nowMinus(640),
    updated_at: nowMinus(640),
  },
  {
    ...base,
    id: "seed-cloud-park",
    title: "雲を飼うベンチ",
    catch_copy: "座ると今日の雲が一匹ついてくる。",
    story:
      "この公園のベンチに座ると、小さな雲が肩の上に降りてくる。雲はその日の気分によって形を変える。",
    latitude: 35.6608,
    longitude: 139.6978,
    seed_text: "この公園に雲を飼うベンチがあったら",
    genre: "cozy",
    place_type: "park",
    mood: "gentle",
    quest: "今日の雲に名前をつけてコメントしてみよう。",
    tags: ["公園", "雲", "ほのぼの"],
    image_theme: "cloud_park",
    generation_type: "template",
    level: 1,
    comment_count: 0,
    believe_count: 8,
    visited_count: 4,
    want_to_go_count: 21,
    author_name: "くもさん",
    created_at: nowMinus(420),
    updated_at: nowMinus(420),
  },
  {
    ...base,
    id: "seed-star-sea",
    title: "空に沈む灯台",
    catch_copy: "夜になると海ではなく空を照らす。",
    story:
      "海辺に立つ古い灯台は、満月の夜だけ空に向かって光を放つ。その光は、迷子になった星を家へ返すためのものだという。",
    latitude: 35.6552,
    longitude: 139.7042,
    seed_text: "この海に空を照らす灯台があったら",
    genre: "fantasy",
    place_type: "sea",
    mood: "mysterious",
    quest: "夜空の中で一番迷っていそうな星を探してみよう。",
    tags: ["海", "星", "灯台"],
    image_theme: "star_sea",
    generation_type: "template",
    level: 3,
    comment_count: 0,
    believe_count: 14,
    visited_count: 9,
    want_to_go_count: 56,
    author_name: "灯台守",
    created_at: nowMinus(300),
    updated_at: nowMinus(300),
  },
  {
    ...base,
    id: "seed-shadow-street",
    title: "夜の商店街",
    catch_copy: "閉店後だけ開く、もう一つの店。",
    story:
      "シャッターの降りた商店街には、夜だけ灯る一軒の店がある。そこで売られているのは、誰かが落とした思い出らしい。",
    latitude: 35.662,
    longitude: 139.7035,
    seed_text: "この商店街に夜だけ開く店があったら",
    genre: "mystery",
    place_type: "shopping_street",
    mood: "mysterious",
    quest: "あなたが取り戻したい思い出をひとつ書いてみよう。",
    tags: ["商店街", "夜", "ミステリー"],
    image_theme: "shadow_street",
    generation_type: "template",
    level: 4,
    comment_count: 0,
    believe_count: 22,
    visited_count: 15,
    want_to_go_count: 88,
    author_name: "夜歩き",
    created_at: nowMinus(220),
    updated_at: nowMinus(220),
  },
  {
    ...base,
    id: "seed-future-school",
    title: "未来の始業式",
    catch_copy: "10年後の自分が先生をしている教室。",
    story:
      "誰もいないはずの校舎で、放課後に黒板へ文字が浮かぶ。それは未来のあなたから、今のあなたへの伝言だという。",
    latitude: 35.657,
    longitude: 139.694,
    seed_text: "この学校に未来とつながる教室があったら",
    genre: "youth",
    place_type: "school",
    mood: "emotional",
    quest: "10年後の自分に伝えたい一言を残してみよう。",
    tags: ["学校", "未来", "青春"],
    image_theme: "future_school",
    generation_type: "template",
    level: 2,
    comment_count: 0,
    believe_count: 11,
    visited_count: 6,
    want_to_go_count: 33,
    author_name: "放課後さん",
    created_at: nowMinus(120),
    updated_at: nowMinus(120),
  },
];
